local poleditor = Reg:PolicyLoad(
    [[HKEY_LOCAL_MACHINE\Tmp_SYSTEM\ControlSet001\Control\ProductOptions]],
    'ProductPolicy')

poleditor:Set("ChangeDesktopBackground-Enabled", 1)
poleditor:Set("FileSystems-ReFs-Enabled", 1)
poleditor:Set("FileSystems-ReFsV1-Enabled", 1)
poleditor:Set("Printing-Spooler-Core-Localspl-Licensing-Enabled", 1)
poleditor:Set("Printing-Spooler-Core-Spoolss-Licensing-Enabled", 1)
poleditor:Set("Printing-Spooler-Pmc-Licensing-Enabled", 1)
poleditor:Set("shell32-license-ShowProductNameOnDesktop", 0)
poleditor:Set("SnippingToolLicensing-Enabled", 1)
poleditor:Set("StickyNotesLicensing-Enabled", 1)
poleditor:Set("Telnet-Client-EnableTelnetClient", 1)
poleditor:Set("TerminalServices-DeviceRedirection-Licenses-PnpRedirectionAllowed", 1)
poleditor:Set("TerminalServices-DeviceRedirection-Licenses-TSAudioCaptureAllowed", 1)
poleditor:Set("TerminalServices-DeviceRedirection-Licenses-TSEasyPrintAllowed", 1)
poleditor:Set("TerminalServices-DeviceRedirection-Licenses-TSMFPluginAllowed", 1)
poleditor:Set("TerminalServices-RDP-7-Advanced-Compression-Allowed", 1)
poleditor:Set("TerminalServices-RemoteApplications-ClientSku-RAILAllowed", 1)
poleditor:Set("TerminalServices-RemoteConnectionManager-45344fe7-00e6-4ac6-9f01-d01fd4ffadfb-MaxSessions", 5)
poleditor:Set("TerminalServices-RemoteConnectionManager-AllowD3DRemoting", 1)
poleditor:Set("TerminalServices-RemoteConnectionManager-AllowMultimon", 1)
poleditor:Set("TerminalServices-RemoteConnectionManager-AllowMultipleSessions", 1)
poleditor:Set("TerminalServices-RemoteConnectionManager-AllowRemoteConnections", 1)
poleditor:Set("TerminalServices-RemoteConnectionManager-b7857721-7a62-4a37-aff3-253fe2b8b0e8-MaxSessions", 1)
poleditor:Set("TerminalServices-RemoteConnectionManager-ce0ad219-4670-4988-98fb-89b14c2f072b-MaxSessions", 1)
poleditor:Set("TerminalServices-RemoteConnectionManager-MaxUserSessions", 5)
poleditor:Save()
